api_root_url: https://robot-dreams-de-api.herokuapp.com

auth:
  endpoint: /auth
  username: rd_dreams
  password: djT6LasE

out_of_stock:
  endpoint: /out_of_stock

dates:
  - "2021-01-02"
  - "2021-01-03"
  - "2021-01-04"
  - "2021-01-05"

storage_dir: ./out_of_stock