pipeline_name: dshop_pipeline

dshop:
  pg_connection_id: postgres_dshop
  tables:
    - aisles
    - clients
    - departments
    - orders
    - products
  

out_of_stock:
  api_root_url: https://robot-dreams-de-api.herokuapp.com

  auth:
    endpoint: /auth
    username: rd_dreams
    password: djT6LasE

  endpoint: /out_of_stock


hdfs:
  bronze_root_dir: /bronze/dshop
  silver_root_dir: /silver/dshop

dwh:
  connection_id: greenplum_olap